[project]
name = "position-baidu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.0",
    "pandas==2.2.2",
    "openpyxl==3.1.2",
    "requests==2.32.3",
]
